### ISSUE TITLE
Roldan Uriel Arcadio Avila 1BS mapa mental

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Roldanuriel#1]
![INVESTIGACION DOCUMENTAL](https://user-images.githubusercontent.com/112295222/187827240-2dba105a-52b9-4216-9ed8-332f8d32ea70.png)

**Comment by Jaczibeth** [comment]
de 20% sacaste 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
